### DISCUSSION TITLE
Running a Docker container

### DISCUSSION THREAD

**Discussion by PlkMarudny** [versity/versitygw#974] [Q&A]
I have a `docker-compose.yaml` file:

```
services:
  versitygw:
    image: ghcr.io/versity/versitygw:latest
    container_name: versitygw
    command: ["./versitygw", "posix", "/data"]
    ports:
      - "7070:7070"
    environment:
      - ROOT_ACCESS_KEY=root
      - ROOT_SECRET_KEY=secret
    volumes:
      - e:/versitygw:/data
  ```

but I am just getting the following output when starting the container: 

```
 ✔ Network versitygw_default  Created                                                                                                                                    0.1s 
 ✔ Container versitygw        Created                                                                                                                                    0.1s 
Attaching to versitygw
versitygw  | NAME:
versitygw  |    versitygw - Versity S3 Gateway
versitygw  | 
versitygw  | USAGE:
versitygw  |    versitygw [global options] command [command options]
versitygw  | 
versitygw  | DESCRIPTION:
versitygw  |    The Versity S3 Gateway is an S3 protocol translator that allows an S3 client
versitygw  |    to access the supported backend storage as if it was a native S3 service.
versitygw  |    VersityGW is an open-source project licensed under the Apache 2.0 License. The
versitygw  |    source code is hosted on GitHub at https://github.com/versity/versitygw, and
versitygw  |    documentation can be found in the GitHub wiki.
versitygw  | 
versitygw  | COMMANDS:
versitygw  |    posix    posix filesystem storage backend
versitygw  |    scoutfs  scoutfs filesystem storage backend
versitygw  |    s3       s3 storage backend
versitygw  |    azure    azure blob storage backend
versitygw  |    admin    admin CLI tool
versitygw  |    test     Client side testing command for the gateway
versitygw  |    utils    utility helper CLI tool
versitygw  |    help, h  Shows a list of commands or help for one command
versitygw  |
versitygw  | GLOBAL OPTIONS:
versitygw  |    --version, -v                                   list versitygw version (default: false)
versitygw  |    --port value, -p value                          gateway listen address <ip>:<port> or :<port> (default: ":7070") [$VGW_PORT]
versitygw  |    --access value, -a value                        root user access key [$ROOT_ACCESS_KEY_ID, $ROOT_ACCESS_KEY]
versitygw  |    --secret value, -s value                        root user secret access key [$ROOT_SECRET_ACCESS_KEY, $ROOT_SECRET_KEY]
versitygw  |    --region value, -r value                        s3 region string (default: "us-east-1") [$VGW_REGION]
versitygw  |    --cert value                                    TLS cert file [$VGW_CERT]
versitygw  |    --key value                                     TLS key file [$VGW_KEY]
versitygw  |    --admin-port value, --ap value                  gateway admin server listen address <ip>:<port> or :<port> [$VGW_ADMIN_PORT]
versitygw  |    --admin-cert value                              TLS cert file for admin server [$VGW_ADMIN_CERT]
versitygw  |    --admin-cert-key value                          TLS key file for admin server [$VGW_ADMIN_CERT_KEY]
versitygw  |    --debug                                         enable debug output (default: false) [$VGW_DEBUG]
versitygw  |    --pprof value                                   enable pprof debug on specified port [$VGW_PPROF]
versitygw  |    --quiet, -q                                     silence stdout request logging output (default: false) [$VGW_QUIET]
versitygw  |    --access-log value                              enable server access logging to specified file [$LOGFILE, $VGW_ACCESS_LOG]
versitygw exited with code 0
```

How to run versitygw container?

**Comment by PlkMarudny** [comment]
Ok, found it in the file `extra/dashboard/docker-compose.yml`, basically the simple `docker-compose.yaml` should be:
```
services:
  versitygw:
    image: ghcr.io/versity/versitygw:latest
    container_name: versitygw
    entrypoint: [ "/app/versitygw"]
    command: >
      posix
      /data
    ports:
      - "7070:7070"
    environment:
      - ROOT_ACCESS_KEY=root
      - ROOT_SECRET_KEY=secret
    volumes:
      - e:/versitygw:/data
```
