### ISSUE TITLE
[Feature] - Docker setup for Github Actions

### ISSUE THREAD

**Issue by madflow** [versity/versitygw#1335]
**Describe the solution you'd like**

- Currently, the Docker image "only" provides the main binary as an entrypoint: https://github.com/versity/versitygw/blob/main/Dockerfile
- This is all fine and dandy.
- With this setup, it is not possible to use  `image: versity/versitygw:latest` in a Github Action, because they do not support "commands". 
- It would be great, if there would be another approach to the Docker setup, where a running server with a i.e. posix backend is running. 
- The configuration could be done with environment variables.
- Maybe something like this as an entrypoint would be possible: https://github.com/versity/versitygw/blob/d7765379448082a15270af153ad2a93c246ce831/extra/versitygw%40.service#L20
- Or seperate Docker builds...

**Additional context**

**Comment by benmcclelland** [comment]
@madflow Do you have an example for how you would like to invoke this in an action yaml file? We can look into if there are examples for how other services have handled this.

**Comment by madflow** [comment]
Unfortunatly, I do not have an example from another similar service.

Maybe similar but probably also not GH action compatible, not sure: https://github.com/seaweedfs/seaweedfs/blob/master/docker/entrypoint.sh

I personally would like to invoke this basically just like "[postgres](https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh)" for instance. Environment variables a heavily used. Given there would be separate Docker builds, for the different backends, and there would be a dedicated "posix" image:


```yaml
jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      s3:
        image: versity/versitygw/posix:latest
        env:
          ROOT_ACCESS_KEY: s3
          ROOT_SECRET_KEY: s3
          VGW_BACKEND_POSIX_ARG_ROOT: /data
          VGW_BACKEND_POSIX_OPT_STH: foo
        ports:
          - 7070:7070
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
```

I am currently just using a `docker-compose.yml` with versitygw in the GH action. This is working for me. An easier usage as an service would still be nice, I would think.
