### ISSUE TITLE
[Feature] - HELM Chart

### ISSUE THREAD

**Issue by ElGigi** [versity/versitygw#980]
My request is for the creation of an official HELM Chart that would allow the gateway to be deployed in Kubernetes.

Example of options:

```yaml
replicas: 3

volumes:
  - name: vol
    hostPath:
      path: /any/path/it/will/be/replaced

versitygw:
    # Path of backend directory
    path: "/any/path/it/will/be/replaced"
    # Secret name for access token
    access_token: ""
    # Secret name for secret key
    secret_key: ""
```
